FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.14

RUN echo "xpack.security.enabled: false" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "bootstrap.system_call_filter: false" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN  /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu && \ 
     /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-phonetic

EXPOSE 9200 9300

